### ISSUE TITLE
sudo: unknown uid 503: who are you?

### ISSUE THREAD

**Issue by ChaseXC** [telerik/nativescript-cloud#192]
I am getting this error when I try to run an iOS cloud build. I first noticed this when my automated build failed on Saturday morning. Here is the full error:

> Build failed. Reason is: Command failed: sudo -EHu builder bash -c \'umask 0002; rm -rf /tmp/builds/_/ce2bb1932534a8ac3b8265d7eefe7cdc7d02cfce/6.3.3/6.3.0/Title1CrateMobileApp && git clone -q --recursive -b master --depth=1 https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sk-builds-706a46759019bcbbb73c5b2ce6ef612a429d963e /tmp/builds/_/ce2bb1932534a8ac3b8265d7eefe7cdc7d02cfce/6.3.3/6.3.0/Title1CrateMobileApp\'\nsudo: unknown uid 503: who are you?\n. Additional information: Command failed: sudo -EHu builder bash -c \'umask 0002; rm -rf /tmp/builds/_/ce2bb1932534a8ac3b8265d7eefe7cdc7d02cfce/6.3.3/6.3.0/Title1CrateMobileApp && git clone -q --recursive -b master --depth=1 https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sk-builds-706a46759019bcbbb73c5b2ce6ef612a429d963e /tmp/builds/_/ce2bb1932534a8ac3b8265d7eefe7cdc7d02cfce/6.3.3/6.3.0/Title1CrateMobileApp\'\nsudo: unknown uid 503: who are you?\n.

**Comment by rosen-vladimirov** [comment]
Thanks @ChaseXC ,
This issue had been resolved earlier today. Can you please try again and see if it works on your side?

**Comment by ChaseXC** [comment]
@rosen-vladimirov Yes it seems to be working! Thank you
